# main.yml
# this file defines a GitHub Actions workflow for CI/CD
# continuoius integration and deployment pipeline

name: CI Pipeline


on:
  push:
    branches:
      - main
  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests with Vitest
        run: npm test

      - name: Build Vite App
        run: npm run build


  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: build-and-test   # ensures this runs only if build-and-test succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          vercel --prod \
                 --token=${{ secrets.VERCEL_TOKEN }} \
                 --confirm \
                 --org ${{ secrets.VERCEL_ORG_ID }} \
                 --project ${{ secrets.VERCEL_PROJECT_ID }}